const CREATEACCOUNTEMPLOYEEROUTE = "/employeer/create";
const CREATEACCOUNTCLIENTROUTE = "/client/create";
const SIGNINEMPLOYEEROUTE = "/employee/login";
const SIGNINCLIENTROUTE = "/client/login";

export {
  CREATEACCOUNTEMPLOYEEROUTE,
  CREATEACCOUNTCLIENTROUTE,
  SIGNINEMPLOYEEROUTE,
  SIGNINCLIENTROUTE,
};
